#!/bin/sh

generate_javadoc() {

  ./gradlew generateJavadoc  

  echo "Removing lines that indicate the timestamp of creation to avoid unncessary change sets"
  sed -i '/Generated by javadoc/d' `find -type f -follow`
}

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

commit_website_files() {  
  git remote add origin-pages https://${GH_TOKEN}@github.com/fmohr/AILibs.git > /dev/null 2>&1  
  if [ -z "${TRAVIS_PULL_REQUEST_BRANCH}" ]; then
    BRANCHTOPUSH=${TRAVIS_BRANCH}
  else
    BRANCHTOPUSH=${TRAVIS_PULL_REQUEST_BRANCH}
  fi
  echo "Last commit message was ${TRAVIS_COMMIT_MESSAGE}"
  echo "Travis branch is \"${TRAVIS_BRANCH}\""
  echo "Travis pull request branch is \"${TRAVIS_PULL_REQUEST_BRANCH}\""
  echo "Checking out ${BRANCHTOPUSH} that is the source here"
  git checkout -B ${BRANCHTOPUSH}
  git add ./\*.html
  git add ./\*.css
  git add ./\*.js
  git add ./\*package-list
  git commit --message "Travis built JavaDoc. ]ci skip["
}

upload_files() {
  git push --set-upstream origin-pages
}

setup_git
generate_javadoc
commit_website_files
upload_files
