#!/bin/sh

generate_javadoc() {

  echo "Generating JavaDoc"
  ./gradlew generateJavadoc  

  echo "Removing lines that indicate the timestamp of creation to avoid unncessary change sets"
  sed -i '/Generated by javadoc/d' `find -type f -follow | grep -v .travis`
  sed -i '/meta name="date" content/d' `find -type f -follow | grep -v .travis`
  
}

setup_git() {
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
}

commit_website_files() {  
  git remote add origin-pages https://${GH_TOKEN}@github.com/fmohr/AILibs.git > /dev/null 2>&1  
  if [ -z "${TRAVIS_PULL_REQUEST_BRANCH}" ]; then
    echo "This is not a pull request check, so not pushing back the built JavaDoc"
    exit
  fi
  echo "Last commit message was ${TRAVIS_COMMIT_MESSAGE}"
  echo "Travis branch is \"${TRAVIS_BRANCH}\""
  echo "Travis pull request branch is \"${TRAVIS_PULL_REQUEST_BRANCH}\""
  echo "Checking out ${TRAVIS_PULL_REQUEST_BRANCH}, which is the source here"
  git checkout -B ${TRAVIS_PULL_REQUEST_BRANCH}
  echo "Staging changes on .html, .css, and .js-files"
  git add ./\*.html
  git add ./\*.css
  git add ./\*.js
  git add ./\*package-list
  
  echo "Change set is as follows:"
  git status
  
  echo "Sending commit"
  git commit --message "Travis built JavaDoc. ]ci skip[" > commit.out
  
  echo "Output of commit log file:"
  cat commit.out
  echo "Now deciding how to proceed ..."
  
  # if nothing has been commited, avoid a push
  if grep -q "nothing to commit" "commit.out"; then
    echo "Nothing comitted, canceling script here to avoid unnecessary push".
	exit 0;
  fi
  if grep -q "nothing added to commit" "commit.out"; then
    echo "Nothing comitted, canceling script here to avoid unnecessary push".
	exit 0;
  fi
  echo "Apparently there are changes, so pushing to upstream"
}

upload_files() {
  echo "Pushing commit to upstream ..."
  git push --set-upstream origin-pages
}

setup_git
generate_javadoc
commit_website_files
upload_files
