// Code generated by Stan version 2.18.0

#include <stan/model/model_header.hpp>

namespace LearningCurve_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "D://Data/Uni/PG/Project/AILibs/softwareconfiguration/LearningCurve/LearningCurve.stan");
    reader.add_event(117, 115, "end", "D://Data/Uni/PG/Project/AILibs/softwareconfiguration/LearningCurve/LearningCurve.stan");
    return reader;
}

template <typename T0__, typename T1__, typename T2__>
typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
log_log_linear(const T0__& a,
                   const T1__& b,
                   const T2__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 4;
        return stan::math::promote_scalar<fun_return_scalar_t__>(stan::math::log(((a * stan::math::log(x)) + b)));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct log_log_linear_functor__ {
    template <typename T0__, typename T1__, typename T2__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
    operator()(const T0__& a,
                   const T1__& b,
                   const T2__& x, std::ostream* pstream__) const {
        return log_log_linear(a, b, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
pow_3(const T0__& c,
          const T1__& a,
          const T2__& alpha,
          const T3__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 8;
        return stan::math::promote_scalar<fun_return_scalar_t__>((c - (a * pow(x,-(alpha)))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct pow_3_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& c,
          const T1__& a,
          const T2__& alpha,
          const T3__& x, std::ostream* pstream__) const {
        return pow_3(c, a, alpha, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
log_power(const T0__& a,
              const T1__& b,
              const T2__& c,
              const T3__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 12;
        return stan::math::promote_scalar<fun_return_scalar_t__>((a / (1 + pow((x / stan::math::exp(b)),c))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct log_power_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& a,
              const T1__& b,
              const T2__& c,
              const T3__& x, std::ostream* pstream__) const {
        return log_power(a, b, c, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
pow_4(const T0__& a,
          const T1__& b,
          const T2__& c,
          const T3__& alpha,
          const T4__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 16;
        return stan::math::promote_scalar<fun_return_scalar_t__>((c - pow(((a * x) + b),-(alpha))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct pow_4_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
    operator()(const T0__& a,
          const T1__& b,
          const T2__& c,
          const T3__& alpha,
          const T4__& x, std::ostream* pstream__) const {
        return pow_4(a, b, c, alpha, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
mmf(const T0__& alpha,
        const T1__& beta,
        const T2__& delta,
        const T3__& kappa,
        const T4__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 20;
        return stan::math::promote_scalar<fun_return_scalar_t__>((alpha - ((alpha - beta) / (1 + pow((kappa * x),delta)))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct mmf_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
    operator()(const T0__& alpha,
        const T1__& beta,
        const T2__& delta,
        const T3__& kappa,
        const T4__& x, std::ostream* pstream__) const {
        return mmf(alpha, beta, delta, kappa, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
exp_4(const T0__& a,
          const T1__& b,
          const T2__& c,
          const T3__& alpha,
          const T4__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 24;
        return stan::math::promote_scalar<fun_return_scalar_t__>((c - stan::math::exp(((-(a) * pow(x,alpha)) + b))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct exp_4_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
    operator()(const T0__& a,
          const T1__& b,
          const T2__& c,
          const T3__& alpha,
          const T4__& x, std::ostream* pstream__) const {
        return exp_4(a, b, c, alpha, x, pstream__);
    }
};

template <typename T0__, typename T1__>
typename boost::math::tools::promote_args<T0__, T1__>::type
f_comb(const std::vector<T0__>& e,
           const T1__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 28;
        return stan::math::promote_scalar<fun_return_scalar_t__>(((((((get_base1(e,1,"e",1) * log_log_linear(get_base1(e,2,"e",1),get_base1(e,3,"e",1),x, pstream__)) + (get_base1(e,4,"e",1) * pow_3(get_base1(e,5,"e",1),get_base1(e,6,"e",1),get_base1(e,7,"e",1),x, pstream__))) + (get_base1(e,8,"e",1) * log_power(get_base1(e,9,"e",1),get_base1(e,10,"e",1),get_base1(e,11,"e",1),x, pstream__))) + (get_base1(e,12,"e",1) * pow_4(get_base1(e,13,"e",1),get_base1(e,14,"e",1),get_base1(e,15,"e",1),get_base1(e,16,"e",1),x, pstream__))) + (get_base1(e,17,"e",1) * mmf(get_base1(e,18,"e",1),get_base1(e,19,"e",1),get_base1(e,20,"e",1),get_base1(e,21,"e",1),x, pstream__))) + (get_base1(e,22,"e",1) * exp_4(get_base1(e,23,"e",1),get_base1(e,24,"e",1),get_base1(e,25,"e",1),get_base1(e,26,"e",1),x, pstream__))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct f_comb_functor__ {
    template <typename T0__, typename T1__>
        typename boost::math::tools::promote_args<T0__, T1__>::type
    operator()(const std::vector<T0__>& e,
           const T1__& x, std::ostream* pstream__) const {
        return f_comb(e, x, pstream__);
    }
};

template <bool propto, typename T0__>
typename boost::math::tools::promote_args<T0__>::type
curveSlopeDist_log(const std::vector<T0__>& e,
                       const int& c,
                       const int& s, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 37;
        if (as_bool(logical_lt(get_base1(e,1,"e",1),0))) {
            current_statement_begin__ = 38;
            return stan::math::promote_scalar<fun_return_scalar_t__>(0);
        }
        current_statement_begin__ = 39;
        if (as_bool(logical_lt(get_base1(e,4,"e",1),0))) {
            current_statement_begin__ = 40;
            return stan::math::promote_scalar<fun_return_scalar_t__>(0);
        }
        current_statement_begin__ = 41;
        if (as_bool(logical_lt(get_base1(e,8,"e",1),0))) {
            current_statement_begin__ = 42;
            return stan::math::promote_scalar<fun_return_scalar_t__>(0);
        }
        current_statement_begin__ = 43;
        if (as_bool(logical_lt(get_base1(e,12,"e",1),0))) {
            current_statement_begin__ = 44;
            return stan::math::promote_scalar<fun_return_scalar_t__>(0);
        }
        current_statement_begin__ = 45;
        if (as_bool(logical_lt(get_base1(e,17,"e",1),0))) {
            current_statement_begin__ = 46;
            return stan::math::promote_scalar<fun_return_scalar_t__>(0);
        }
        current_statement_begin__ = 47;
        if (as_bool(logical_lt(get_base1(e,22,"e",1),0))) {
            current_statement_begin__ = 48;
            return stan::math::promote_scalar<fun_return_scalar_t__>(0);
        }
        current_statement_begin__ = 49;
        for (int k = 1; k <= c; ++k) {
            current_statement_begin__ = 50;
            if (as_bool(logical_gt(f_comb(e,(k * s), pstream__),f_comb(e,((s * k) + s), pstream__)))) {
                current_statement_begin__ = 51;
                return stan::math::promote_scalar<fun_return_scalar_t__>(0);
            }
        }
        current_statement_begin__ = 52;
        return stan::math::promote_scalar<fun_return_scalar_t__>(1);
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
template <typename T0__>
typename boost::math::tools::promote_args<T0__>::type
curveSlopeDist_log(const std::vector<T0__>& e,
                       const int& c,
                       const int& s, std::ostream* pstream__) {
    return curveSlopeDist_log<false>(e,c,s, pstream__);
}


struct curveSlopeDist_log_functor__ {
    template <bool propto, typename T0__>
        typename boost::math::tools::promote_args<T0__>::type
    operator()(const std::vector<T0__>& e,
                       const int& c,
                       const int& s, std::ostream* pstream__) const {
        return curveSlopeDist_log(e, c, s, pstream__);
    }
};

class LearningCurve_model : public prob_grad {
private:
    int N;
    int c;
    int s;
    vector_d x;
    vector_d y;
public:
    LearningCurve_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    LearningCurve_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "LearningCurve_model_namespace::LearningCurve_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 57;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 58;
            context__.validate_dims("data initialization", "c", "int", context__.to_vec());
            c = int(0);
            vals_i__ = context__.vals_i("c");
            pos__ = 0;
            c = vals_i__[pos__++];
            current_statement_begin__ = 59;
            context__.validate_dims("data initialization", "s", "int", context__.to_vec());
            s = int(0);
            vals_i__ = context__.vals_i("s");
            pos__ = 0;
            s = vals_i__[pos__++];
            current_statement_begin__ = 60;
            validate_non_negative_index("x", "N", N);
            context__.validate_dims("data initialization", "x", "vector_d", context__.to_vec(N));
            validate_non_negative_index("x", "N", N);
            x = vector_d(static_cast<Eigen::VectorXd::Index>(N));
            vals_r__ = context__.vals_r("x");
            pos__ = 0;
            size_t x_i_vec_lim__ = N;
            for (size_t i_vec__ = 0; i_vec__ < x_i_vec_lim__; ++i_vec__) {
                x[i_vec__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 61;
            validate_non_negative_index("y", "N", N);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(N));
            validate_non_negative_index("y", "N", N);
            y = vector_d(static_cast<Eigen::VectorXd::Index>(N));
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_i_vec_lim__ = N;
            for (size_t i_vec__ = 0; i_vec__ < y_i_vec_lim__; ++i_vec__) {
                y[i_vec__] = vals_r__[pos__++];
            }

            // validate, data variables
            current_statement_begin__ = 57;
            current_statement_begin__ = 58;
            current_statement_begin__ = 59;
            current_statement_begin__ = 60;
            current_statement_begin__ = 61;
            // initialize data variables


            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 65;
            validate_non_negative_index("e", "26", 26);
            num_params_r__ += 26;
            current_statement_begin__ = 94;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~LearningCurve_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("e")))
            throw std::runtime_error("variable e missing");
        vals_r__ = context__.vals_r("e");
        pos__ = 0U;
        validate_non_negative_index("e", "26", 26);
        context__.validate_dims("initialization", "e", "double", context__.to_vec(26));
        std::vector<double> e(26,double(0));
        for (int i0__ = 0U; i0__ < 26; ++i0__)
            e[i0__] = vals_r__[pos__++];
        for (int i0__ = 0U; i0__ < 26; ++i0__)
            try {
            writer__.scalar_unconstrain(e[i0__]);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable e: ") + e.what());
        }

        if (!(context__.contains_r("sigma")))
            throw std::runtime_error("variable sigma missing");
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigma);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigma: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);

            vector<local_scalar_t__> e;
            size_t dim_e_0__ = 26;
            e.reserve(dim_e_0__);
            for (size_t k_0__ = 0; k_0__ < dim_e_0__; ++k_0__) {
                if (jacobian__)
                    e.push_back(in__.scalar_constrain(lp__));
                else
                    e.push_back(in__.scalar_constrain());
            }

            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0,lp__);
            else
                sigma = in__.scalar_lb_constrain(0);


            // transformed parameters



            // validate transformed parameters

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            // model body
            {
            current_statement_begin__ = 101;
            validate_non_negative_index("ypred", "N", N);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  ypred(static_cast<Eigen::VectorXd::Index>(N));
            (void) ypred;  // dummy to suppress unused var warning

            stan::math::initialize(ypred, DUMMY_VAR__);
            stan::math::fill(ypred,DUMMY_VAR__);


            current_statement_begin__ = 103;
            lp_accum__.add(normal_log<propto__>(sigma, 0, 1));
            current_statement_begin__ = 106;
            lp_accum__.add(curveSlopeDist_log<propto__>(e, c, s, pstream__));
            current_statement_begin__ = 109;
            for (int n = 1; n <= N; ++n) {
                current_statement_begin__ = 110;
                stan::model::assign(ypred, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            f_comb(e,get_base1(x,n,"x",1), pstream__), 
                            "assigning variable ypred");
            }
            current_statement_begin__ = 112;
            lp_accum__.add(normal_log<propto__>(y, ypred, sigma));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("e");
        names__.push_back("sigma");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(26);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "LearningCurve_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector<double> e;
        size_t dim_e_0__ = 26;
        for (size_t k_0__ = 0; k_0__ < dim_e_0__; ++k_0__) {
            e.push_back(in__.scalar_constrain());
        }
        double sigma = in__.scalar_lb_constrain(0);
            for (int k_0__ = 0; k_0__ < 26; ++k_0__) {
            vars__.push_back(e[k_0__]);
            }
        vars__.push_back(sigma);

        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {



            // validate transformed parameters

            // write transformed parameters
            if (include_tparams__) {
            }
            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "LearningCurve_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= 26; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }


        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= 26; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "e" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }


        if (!include_gqs__) return;
    }

}; // model

}

typedef LearningCurve_model_namespace::LearningCurve_model stan_model;

