// Code generated by Stan version 2.18.0

#include <stan/model/model_header.hpp>

namespace LearningCurveOld_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "D://Data/Uni/PG/Project/AILibs/softwareconfiguration/LearningCurve/LearningCurveOld.stan");
    reader.add_event(145, 143, "end", "D://Data/Uni/PG/Project/AILibs/softwareconfiguration/LearningCurve/LearningCurveOld.stan");
    return reader;
}

template <typename T0__, typename T1__, typename T2__>
typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
log_log_linear(const T0__& a,
                   const T1__& b,
                   const T2__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 4;
        return stan::math::promote_scalar<fun_return_scalar_t__>(stan::math::log(((a * stan::math::log(x)) + b)));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct log_log_linear_functor__ {
    template <typename T0__, typename T1__, typename T2__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
    operator()(const T0__& a,
                   const T1__& b,
                   const T2__& x, std::ostream* pstream__) const {
        return log_log_linear(a, b, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
pow_3(const T0__& c,
          const T1__& a,
          const T2__& alpha,
          const T3__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 8;
        return stan::math::promote_scalar<fun_return_scalar_t__>((c - (a * pow(x,-(alpha)))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct pow_3_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& c,
          const T1__& a,
          const T2__& alpha,
          const T3__& x, std::ostream* pstream__) const {
        return pow_3(c, a, alpha, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
log_power(const T0__& a,
              const T1__& b,
              const T2__& c,
              const T3__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 12;
        return stan::math::promote_scalar<fun_return_scalar_t__>((a / (1 + pow((x / stan::math::exp(b)),c))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct log_power_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& a,
              const T1__& b,
              const T2__& c,
              const T3__& x, std::ostream* pstream__) const {
        return log_power(a, b, c, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
pow_4(const T0__& a,
          const T1__& b,
          const T2__& c,
          const T3__& alpha,
          const T4__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 16;
        return stan::math::promote_scalar<fun_return_scalar_t__>((c - pow(((a * x) + b),-(alpha))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct pow_4_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
    operator()(const T0__& a,
          const T1__& b,
          const T2__& c,
          const T3__& alpha,
          const T4__& x, std::ostream* pstream__) const {
        return pow_4(a, b, c, alpha, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
mmf(const T0__& alpha,
        const T1__& beta,
        const T2__& delta,
        const T3__& kappa,
        const T4__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 20;
        return stan::math::promote_scalar<fun_return_scalar_t__>((alpha - ((alpha - beta) / (1 + pow((kappa * x),delta)))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct mmf_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
    operator()(const T0__& alpha,
        const T1__& beta,
        const T2__& delta,
        const T3__& kappa,
        const T4__& x, std::ostream* pstream__) const {
        return mmf(alpha, beta, delta, kappa, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
exp_4(const T0__& a,
          const T1__& b,
          const T2__& c,
          const T3__& alpha,
          const T4__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 24;
        return stan::math::promote_scalar<fun_return_scalar_t__>((c - stan::math::exp(((-(a) * pow(x,alpha)) + b))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct exp_4_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__>::type>::type
    operator()(const T0__& a,
          const T1__& b,
          const T2__& c,
          const T3__& alpha,
          const T4__& x, std::ostream* pstream__) const {
        return exp_4(a, b, c, alpha, x, pstream__);
    }
};

template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__, typename T10__, typename T11__, typename T12__, typename T13__, typename T14__, typename T15__, typename T16__, typename T17__, typename T18__, typename T19__, typename T20__, typename T21__, typename T22__, typename T23__, typename T24__, typename T25__, typename T26__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__, T10__, T11__, typename boost::math::tools::promote_args<T12__, T13__, T14__, T15__, typename boost::math::tools::promote_args<T16__, T17__, T18__, T19__, typename boost::math::tools::promote_args<T20__, T21__, T22__, T23__, typename boost::math::tools::promote_args<T24__, T25__, T26__>::type>::type>::type>::type>::type>::type>::type
f_comb(const T0__& w_0,
           const T1__& w_1,
           const T2__& w_2,
           const T3__& w_3,
           const T4__& w_4,
           const T5__& w_5,
           const T6__& a_0,
           const T7__& b_0,
           const T8__& c_1,
           const T9__& a_1,
           const T10__& alpha_1,
           const T11__& a_2,
           const T12__& b_2,
           const T13__& c_2,
           const T14__& a_3,
           const T15__& b_3,
           const T16__& c_3,
           const T17__& alpha_3,
           const T18__& alpha_4,
           const T19__& beta_4,
           const T20__& delta_4,
           const T21__& kappa_4,
           const T22__& a_5,
           const T23__& b_5,
           const T24__& c_5,
           const T25__& alpha_5,
           const T26__& x, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__, T10__, T11__, typename boost::math::tools::promote_args<T12__, T13__, T14__, T15__, typename boost::math::tools::promote_args<T16__, T17__, T18__, T19__, typename boost::math::tools::promote_args<T20__, T21__, T22__, T23__, typename boost::math::tools::promote_args<T24__, T25__, T26__>::type>::type>::type>::type>::type>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 28;
        return stan::math::promote_scalar<fun_return_scalar_t__>(((((((w_0 * log_log_linear(a_0,b_0,x, pstream__)) + (w_1 * pow_3(c_1,a_1,alpha_1,x, pstream__))) + (w_2 * log_power(a_2,b_2,c_2,x, pstream__))) + (w_3 * pow_4(a_3,b_3,c_3,alpha_3,x, pstream__))) + (w_4 * mmf(alpha_4,beta_4,delta_4,kappa_4,x, pstream__))) + (w_5 * exp_4(a_5,b_5,c_5,alpha_5,x, pstream__))));
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}


struct f_comb_functor__ {
    template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__, typename T10__, typename T11__, typename T12__, typename T13__, typename T14__, typename T15__, typename T16__, typename T17__, typename T18__, typename T19__, typename T20__, typename T21__, typename T22__, typename T23__, typename T24__, typename T25__, typename T26__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__, T10__, T11__, typename boost::math::tools::promote_args<T12__, T13__, T14__, T15__, typename boost::math::tools::promote_args<T16__, T17__, T18__, T19__, typename boost::math::tools::promote_args<T20__, T21__, T22__, T23__, typename boost::math::tools::promote_args<T24__, T25__, T26__>::type>::type>::type>::type>::type>::type>::type
    operator()(const T0__& w_0,
           const T1__& w_1,
           const T2__& w_2,
           const T3__& w_3,
           const T4__& w_4,
           const T5__& w_5,
           const T6__& a_0,
           const T7__& b_0,
           const T8__& c_1,
           const T9__& a_1,
           const T10__& alpha_1,
           const T11__& a_2,
           const T12__& b_2,
           const T13__& c_2,
           const T14__& a_3,
           const T15__& b_3,
           const T16__& c_3,
           const T17__& alpha_3,
           const T18__& alpha_4,
           const T19__& beta_4,
           const T20__& delta_4,
           const T21__& kappa_4,
           const T22__& a_5,
           const T23__& b_5,
           const T24__& c_5,
           const T25__& alpha_5,
           const T26__& x, std::ostream* pstream__) const {
        return f_comb(w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, x, pstream__);
    }
};

template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__, typename T10__, typename T11__, typename T12__, typename T13__, typename T14__, typename T15__, typename T16__, typename T17__, typename T18__, typename T19__, typename T20__, typename T21__, typename T22__, typename T23__, typename T24__, typename T25__, typename T26__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__, T10__, T11__, typename boost::math::tools::promote_args<T12__, T13__, T14__, T15__, typename boost::math::tools::promote_args<T16__, T17__, T18__, T19__, typename boost::math::tools::promote_args<T20__, T21__, T22__, T23__, typename boost::math::tools::promote_args<T24__, T25__, T26__>::type>::type>::type>::type>::type>::type>::type
curveSlopeDist_log(const T0__& tmp,
                       const T1__& w_0,
                       const T2__& w_1,
                       const T3__& w_2,
                       const T4__& w_3,
                       const T5__& w_4,
                       const T6__& w_5,
                       const T7__& a_0,
                       const T8__& b_0,
                       const T9__& c_1,
                       const T10__& a_1,
                       const T11__& alpha_1,
                       const T12__& a_2,
                       const T13__& b_2,
                       const T14__& c_2,
                       const T15__& a_3,
                       const T16__& b_3,
                       const T17__& c_3,
                       const T18__& alpha_3,
                       const T19__& alpha_4,
                       const T20__& beta_4,
                       const T21__& delta_4,
                       const T22__& kappa_4,
                       const T23__& a_5,
                       const T24__& b_5,
                       const T25__& c_5,
                       const T26__& alpha_5,
                       const int& m, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__, T10__, T11__, typename boost::math::tools::promote_args<T12__, T13__, T14__, T15__, typename boost::math::tools::promote_args<T16__, T17__, T18__, T19__, typename boost::math::tools::promote_args<T20__, T21__, T22__, T23__, typename boost::math::tools::promote_args<T24__, T25__, T26__>::type>::type>::type>::type>::type>::type>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

    int current_statement_begin__ = -1;
    try {

        current_statement_begin__ = 32;
        for (int k = 1; k <= 5; ++k) {
            current_statement_begin__ = 33;
            if (as_bool(logical_gt(f_comb(w_0,w_1,w_2,w_3,w_4,w_5,a_0,b_0,c_1,a_1,alpha_1,a_2,b_2,c_2,a_3,b_3,c_3,alpha_3,alpha_4,beta_4,delta_4,kappa_4,a_5,b_5,c_5,alpha_5,(k * 400), pstream__),f_comb(w_0,w_1,w_2,w_3,w_4,w_5,a_0,b_0,c_1,a_1,alpha_1,a_2,b_2,c_2,a_3,b_3,c_3,alpha_3,alpha_4,beta_4,delta_4,kappa_4,a_5,b_5,c_5,alpha_5,((400 * k) + 400), pstream__)))) {
                current_statement_begin__ = 34;
                return stan::math::promote_scalar<fun_return_scalar_t__>(0);
            }
        }
        current_statement_begin__ = 35;
        return stan::math::promote_scalar<fun_return_scalar_t__>(1);
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
template <typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__, typename T10__, typename T11__, typename T12__, typename T13__, typename T14__, typename T15__, typename T16__, typename T17__, typename T18__, typename T19__, typename T20__, typename T21__, typename T22__, typename T23__, typename T24__, typename T25__, typename T26__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__, T10__, T11__, typename boost::math::tools::promote_args<T12__, T13__, T14__, T15__, typename boost::math::tools::promote_args<T16__, T17__, T18__, T19__, typename boost::math::tools::promote_args<T20__, T21__, T22__, T23__, typename boost::math::tools::promote_args<T24__, T25__, T26__>::type>::type>::type>::type>::type>::type>::type
curveSlopeDist_log(const T0__& tmp,
                       const T1__& w_0,
                       const T2__& w_1,
                       const T3__& w_2,
                       const T4__& w_3,
                       const T5__& w_4,
                       const T6__& w_5,
                       const T7__& a_0,
                       const T8__& b_0,
                       const T9__& c_1,
                       const T10__& a_1,
                       const T11__& alpha_1,
                       const T12__& a_2,
                       const T13__& b_2,
                       const T14__& c_2,
                       const T15__& a_3,
                       const T16__& b_3,
                       const T17__& c_3,
                       const T18__& alpha_3,
                       const T19__& alpha_4,
                       const T20__& beta_4,
                       const T21__& delta_4,
                       const T22__& kappa_4,
                       const T23__& a_5,
                       const T24__& b_5,
                       const T25__& c_5,
                       const T26__& alpha_5,
                       const int& m, std::ostream* pstream__) {
    return curveSlopeDist_log<false>(tmp,w_0,w_1,w_2,w_3,w_4,w_5,a_0,b_0,c_1,a_1,alpha_1,a_2,b_2,c_2,a_3,b_3,c_3,alpha_3,alpha_4,beta_4,delta_4,kappa_4,a_5,b_5,c_5,alpha_5,m, pstream__);
}


struct curveSlopeDist_log_functor__ {
    template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__, typename T4__, typename T5__, typename T6__, typename T7__, typename T8__, typename T9__, typename T10__, typename T11__, typename T12__, typename T13__, typename T14__, typename T15__, typename T16__, typename T17__, typename T18__, typename T19__, typename T20__, typename T21__, typename T22__, typename T23__, typename T24__, typename T25__, typename T26__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__, typename boost::math::tools::promote_args<T4__, T5__, T6__, T7__, typename boost::math::tools::promote_args<T8__, T9__, T10__, T11__, typename boost::math::tools::promote_args<T12__, T13__, T14__, T15__, typename boost::math::tools::promote_args<T16__, T17__, T18__, T19__, typename boost::math::tools::promote_args<T20__, T21__, T22__, T23__, typename boost::math::tools::promote_args<T24__, T25__, T26__>::type>::type>::type>::type>::type>::type>::type
    operator()(const T0__& tmp,
                       const T1__& w_0,
                       const T2__& w_1,
                       const T3__& w_2,
                       const T4__& w_3,
                       const T5__& w_4,
                       const T6__& w_5,
                       const T7__& a_0,
                       const T8__& b_0,
                       const T9__& c_1,
                       const T10__& a_1,
                       const T11__& alpha_1,
                       const T12__& a_2,
                       const T13__& b_2,
                       const T14__& c_2,
                       const T15__& a_3,
                       const T16__& b_3,
                       const T17__& c_3,
                       const T18__& alpha_3,
                       const T19__& alpha_4,
                       const T20__& beta_4,
                       const T21__& delta_4,
                       const T22__& kappa_4,
                       const T23__& a_5,
                       const T24__& b_5,
                       const T25__& c_5,
                       const T26__& alpha_5,
                       const int& m, std::ostream* pstream__) const {
        return curveSlopeDist_log(tmp, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__);
    }
};

class LearningCurveOld_model : public prob_grad {
private:
    int N;
    int m;
    vector_d x;
    vector_d y;
public:
    LearningCurveOld_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    LearningCurveOld_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "LearningCurveOld_model_namespace::LearningCurveOld_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 40;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 41;
            context__.validate_dims("data initialization", "m", "int", context__.to_vec());
            m = int(0);
            vals_i__ = context__.vals_i("m");
            pos__ = 0;
            m = vals_i__[pos__++];
            current_statement_begin__ = 42;
            validate_non_negative_index("x", "N", N);
            context__.validate_dims("data initialization", "x", "vector_d", context__.to_vec(N));
            validate_non_negative_index("x", "N", N);
            x = vector_d(static_cast<Eigen::VectorXd::Index>(N));
            vals_r__ = context__.vals_r("x");
            pos__ = 0;
            size_t x_i_vec_lim__ = N;
            for (size_t i_vec__ = 0; i_vec__ < x_i_vec_lim__; ++i_vec__) {
                x[i_vec__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 43;
            validate_non_negative_index("y", "N", N);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(N));
            validate_non_negative_index("y", "N", N);
            y = vector_d(static_cast<Eigen::VectorXd::Index>(N));
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_i_vec_lim__ = N;
            for (size_t i_vec__ = 0; i_vec__ < y_i_vec_lim__; ++i_vec__) {
                y[i_vec__] = vals_r__[pos__++];
            }

            // validate, data variables
            current_statement_begin__ = 40;
            current_statement_begin__ = 41;
            current_statement_begin__ = 42;
            current_statement_begin__ = 43;
            // initialize data variables


            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 48;
            ++num_params_r__;
            current_statement_begin__ = 49;
            ++num_params_r__;
            current_statement_begin__ = 50;
            ++num_params_r__;
            current_statement_begin__ = 51;
            ++num_params_r__;
            current_statement_begin__ = 52;
            ++num_params_r__;
            current_statement_begin__ = 53;
            ++num_params_r__;
            current_statement_begin__ = 54;
            ++num_params_r__;
            current_statement_begin__ = 55;
            ++num_params_r__;
            current_statement_begin__ = 56;
            ++num_params_r__;
            current_statement_begin__ = 57;
            ++num_params_r__;
            current_statement_begin__ = 58;
            ++num_params_r__;
            current_statement_begin__ = 59;
            ++num_params_r__;
            current_statement_begin__ = 60;
            ++num_params_r__;
            current_statement_begin__ = 61;
            ++num_params_r__;
            current_statement_begin__ = 62;
            ++num_params_r__;
            current_statement_begin__ = 63;
            ++num_params_r__;
            current_statement_begin__ = 64;
            ++num_params_r__;
            current_statement_begin__ = 65;
            ++num_params_r__;
            current_statement_begin__ = 66;
            ++num_params_r__;
            current_statement_begin__ = 67;
            ++num_params_r__;
            current_statement_begin__ = 68;
            ++num_params_r__;
            current_statement_begin__ = 69;
            ++num_params_r__;
            current_statement_begin__ = 70;
            ++num_params_r__;
            current_statement_begin__ = 71;
            ++num_params_r__;
            current_statement_begin__ = 72;
            ++num_params_r__;
            current_statement_begin__ = 73;
            ++num_params_r__;
            current_statement_begin__ = 75;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~LearningCurveOld_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("w_0")))
            throw std::runtime_error("variable w_0 missing");
        vals_r__ = context__.vals_r("w_0");
        pos__ = 0U;
        context__.validate_dims("initialization", "w_0", "double", context__.to_vec());
        double w_0(0);
        w_0 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,w_0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w_0: ") + e.what());
        }

        if (!(context__.contains_r("a_0")))
            throw std::runtime_error("variable a_0 missing");
        vals_r__ = context__.vals_r("a_0");
        pos__ = 0U;
        context__.validate_dims("initialization", "a_0", "double", context__.to_vec());
        double a_0(0);
        a_0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(a_0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable a_0: ") + e.what());
        }

        if (!(context__.contains_r("b_0")))
            throw std::runtime_error("variable b_0 missing");
        vals_r__ = context__.vals_r("b_0");
        pos__ = 0U;
        context__.validate_dims("initialization", "b_0", "double", context__.to_vec());
        double b_0(0);
        b_0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(b_0);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b_0: ") + e.what());
        }

        if (!(context__.contains_r("w_1")))
            throw std::runtime_error("variable w_1 missing");
        vals_r__ = context__.vals_r("w_1");
        pos__ = 0U;
        context__.validate_dims("initialization", "w_1", "double", context__.to_vec());
        double w_1(0);
        w_1 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,w_1);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w_1: ") + e.what());
        }

        if (!(context__.contains_r("c_1")))
            throw std::runtime_error("variable c_1 missing");
        vals_r__ = context__.vals_r("c_1");
        pos__ = 0U;
        context__.validate_dims("initialization", "c_1", "double", context__.to_vec());
        double c_1(0);
        c_1 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(c_1);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable c_1: ") + e.what());
        }

        if (!(context__.contains_r("a_1")))
            throw std::runtime_error("variable a_1 missing");
        vals_r__ = context__.vals_r("a_1");
        pos__ = 0U;
        context__.validate_dims("initialization", "a_1", "double", context__.to_vec());
        double a_1(0);
        a_1 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(a_1);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable a_1: ") + e.what());
        }

        if (!(context__.contains_r("alpha_1")))
            throw std::runtime_error("variable alpha_1 missing");
        vals_r__ = context__.vals_r("alpha_1");
        pos__ = 0U;
        context__.validate_dims("initialization", "alpha_1", "double", context__.to_vec());
        double alpha_1(0);
        alpha_1 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(alpha_1);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable alpha_1: ") + e.what());
        }

        if (!(context__.contains_r("w_2")))
            throw std::runtime_error("variable w_2 missing");
        vals_r__ = context__.vals_r("w_2");
        pos__ = 0U;
        context__.validate_dims("initialization", "w_2", "double", context__.to_vec());
        double w_2(0);
        w_2 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,w_2);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w_2: ") + e.what());
        }

        if (!(context__.contains_r("a_2")))
            throw std::runtime_error("variable a_2 missing");
        vals_r__ = context__.vals_r("a_2");
        pos__ = 0U;
        context__.validate_dims("initialization", "a_2", "double", context__.to_vec());
        double a_2(0);
        a_2 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(a_2);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable a_2: ") + e.what());
        }

        if (!(context__.contains_r("b_2")))
            throw std::runtime_error("variable b_2 missing");
        vals_r__ = context__.vals_r("b_2");
        pos__ = 0U;
        context__.validate_dims("initialization", "b_2", "double", context__.to_vec());
        double b_2(0);
        b_2 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(b_2);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b_2: ") + e.what());
        }

        if (!(context__.contains_r("c_2")))
            throw std::runtime_error("variable c_2 missing");
        vals_r__ = context__.vals_r("c_2");
        pos__ = 0U;
        context__.validate_dims("initialization", "c_2", "double", context__.to_vec());
        double c_2(0);
        c_2 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(c_2);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable c_2: ") + e.what());
        }

        if (!(context__.contains_r("w_3")))
            throw std::runtime_error("variable w_3 missing");
        vals_r__ = context__.vals_r("w_3");
        pos__ = 0U;
        context__.validate_dims("initialization", "w_3", "double", context__.to_vec());
        double w_3(0);
        w_3 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,w_3);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w_3: ") + e.what());
        }

        if (!(context__.contains_r("a_3")))
            throw std::runtime_error("variable a_3 missing");
        vals_r__ = context__.vals_r("a_3");
        pos__ = 0U;
        context__.validate_dims("initialization", "a_3", "double", context__.to_vec());
        double a_3(0);
        a_3 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(a_3);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable a_3: ") + e.what());
        }

        if (!(context__.contains_r("b_3")))
            throw std::runtime_error("variable b_3 missing");
        vals_r__ = context__.vals_r("b_3");
        pos__ = 0U;
        context__.validate_dims("initialization", "b_3", "double", context__.to_vec());
        double b_3(0);
        b_3 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(b_3);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b_3: ") + e.what());
        }

        if (!(context__.contains_r("c_3")))
            throw std::runtime_error("variable c_3 missing");
        vals_r__ = context__.vals_r("c_3");
        pos__ = 0U;
        context__.validate_dims("initialization", "c_3", "double", context__.to_vec());
        double c_3(0);
        c_3 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(c_3);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable c_3: ") + e.what());
        }

        if (!(context__.contains_r("alpha_3")))
            throw std::runtime_error("variable alpha_3 missing");
        vals_r__ = context__.vals_r("alpha_3");
        pos__ = 0U;
        context__.validate_dims("initialization", "alpha_3", "double", context__.to_vec());
        double alpha_3(0);
        alpha_3 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(alpha_3);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable alpha_3: ") + e.what());
        }

        if (!(context__.contains_r("w_4")))
            throw std::runtime_error("variable w_4 missing");
        vals_r__ = context__.vals_r("w_4");
        pos__ = 0U;
        context__.validate_dims("initialization", "w_4", "double", context__.to_vec());
        double w_4(0);
        w_4 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,w_4);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w_4: ") + e.what());
        }

        if (!(context__.contains_r("alpha_4")))
            throw std::runtime_error("variable alpha_4 missing");
        vals_r__ = context__.vals_r("alpha_4");
        pos__ = 0U;
        context__.validate_dims("initialization", "alpha_4", "double", context__.to_vec());
        double alpha_4(0);
        alpha_4 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(alpha_4);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable alpha_4: ") + e.what());
        }

        if (!(context__.contains_r("beta_4")))
            throw std::runtime_error("variable beta_4 missing");
        vals_r__ = context__.vals_r("beta_4");
        pos__ = 0U;
        context__.validate_dims("initialization", "beta_4", "double", context__.to_vec());
        double beta_4(0);
        beta_4 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(beta_4);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable beta_4: ") + e.what());
        }

        if (!(context__.contains_r("delta_4")))
            throw std::runtime_error("variable delta_4 missing");
        vals_r__ = context__.vals_r("delta_4");
        pos__ = 0U;
        context__.validate_dims("initialization", "delta_4", "double", context__.to_vec());
        double delta_4(0);
        delta_4 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(delta_4);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable delta_4: ") + e.what());
        }

        if (!(context__.contains_r("kappa_4")))
            throw std::runtime_error("variable kappa_4 missing");
        vals_r__ = context__.vals_r("kappa_4");
        pos__ = 0U;
        context__.validate_dims("initialization", "kappa_4", "double", context__.to_vec());
        double kappa_4(0);
        kappa_4 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(kappa_4);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable kappa_4: ") + e.what());
        }

        if (!(context__.contains_r("w_5")))
            throw std::runtime_error("variable w_5 missing");
        vals_r__ = context__.vals_r("w_5");
        pos__ = 0U;
        context__.validate_dims("initialization", "w_5", "double", context__.to_vec());
        double w_5(0);
        w_5 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,w_5);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable w_5: ") + e.what());
        }

        if (!(context__.contains_r("a_5")))
            throw std::runtime_error("variable a_5 missing");
        vals_r__ = context__.vals_r("a_5");
        pos__ = 0U;
        context__.validate_dims("initialization", "a_5", "double", context__.to_vec());
        double a_5(0);
        a_5 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(a_5);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable a_5: ") + e.what());
        }

        if (!(context__.contains_r("b_5")))
            throw std::runtime_error("variable b_5 missing");
        vals_r__ = context__.vals_r("b_5");
        pos__ = 0U;
        context__.validate_dims("initialization", "b_5", "double", context__.to_vec());
        double b_5(0);
        b_5 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(b_5);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b_5: ") + e.what());
        }

        if (!(context__.contains_r("c_5")))
            throw std::runtime_error("variable c_5 missing");
        vals_r__ = context__.vals_r("c_5");
        pos__ = 0U;
        context__.validate_dims("initialization", "c_5", "double", context__.to_vec());
        double c_5(0);
        c_5 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(c_5);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable c_5: ") + e.what());
        }

        if (!(context__.contains_r("alpha_5")))
            throw std::runtime_error("variable alpha_5 missing");
        vals_r__ = context__.vals_r("alpha_5");
        pos__ = 0U;
        context__.validate_dims("initialization", "alpha_5", "double", context__.to_vec());
        double alpha_5(0);
        alpha_5 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(alpha_5);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable alpha_5: ") + e.what());
        }

        if (!(context__.contains_r("sigma")))
            throw std::runtime_error("variable sigma missing");
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigma);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigma: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);

            local_scalar_t__ w_0;
            (void) w_0;  // dummy to suppress unused var warning
            if (jacobian__)
                w_0 = in__.scalar_lb_constrain(0,lp__);
            else
                w_0 = in__.scalar_lb_constrain(0);

            local_scalar_t__ a_0;
            (void) a_0;  // dummy to suppress unused var warning
            if (jacobian__)
                a_0 = in__.scalar_constrain(lp__);
            else
                a_0 = in__.scalar_constrain();

            local_scalar_t__ b_0;
            (void) b_0;  // dummy to suppress unused var warning
            if (jacobian__)
                b_0 = in__.scalar_constrain(lp__);
            else
                b_0 = in__.scalar_constrain();

            local_scalar_t__ w_1;
            (void) w_1;  // dummy to suppress unused var warning
            if (jacobian__)
                w_1 = in__.scalar_lb_constrain(0,lp__);
            else
                w_1 = in__.scalar_lb_constrain(0);

            local_scalar_t__ c_1;
            (void) c_1;  // dummy to suppress unused var warning
            if (jacobian__)
                c_1 = in__.scalar_constrain(lp__);
            else
                c_1 = in__.scalar_constrain();

            local_scalar_t__ a_1;
            (void) a_1;  // dummy to suppress unused var warning
            if (jacobian__)
                a_1 = in__.scalar_constrain(lp__);
            else
                a_1 = in__.scalar_constrain();

            local_scalar_t__ alpha_1;
            (void) alpha_1;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha_1 = in__.scalar_constrain(lp__);
            else
                alpha_1 = in__.scalar_constrain();

            local_scalar_t__ w_2;
            (void) w_2;  // dummy to suppress unused var warning
            if (jacobian__)
                w_2 = in__.scalar_lb_constrain(0,lp__);
            else
                w_2 = in__.scalar_lb_constrain(0);

            local_scalar_t__ a_2;
            (void) a_2;  // dummy to suppress unused var warning
            if (jacobian__)
                a_2 = in__.scalar_constrain(lp__);
            else
                a_2 = in__.scalar_constrain();

            local_scalar_t__ b_2;
            (void) b_2;  // dummy to suppress unused var warning
            if (jacobian__)
                b_2 = in__.scalar_constrain(lp__);
            else
                b_2 = in__.scalar_constrain();

            local_scalar_t__ c_2;
            (void) c_2;  // dummy to suppress unused var warning
            if (jacobian__)
                c_2 = in__.scalar_constrain(lp__);
            else
                c_2 = in__.scalar_constrain();

            local_scalar_t__ w_3;
            (void) w_3;  // dummy to suppress unused var warning
            if (jacobian__)
                w_3 = in__.scalar_lb_constrain(0,lp__);
            else
                w_3 = in__.scalar_lb_constrain(0);

            local_scalar_t__ a_3;
            (void) a_3;  // dummy to suppress unused var warning
            if (jacobian__)
                a_3 = in__.scalar_constrain(lp__);
            else
                a_3 = in__.scalar_constrain();

            local_scalar_t__ b_3;
            (void) b_3;  // dummy to suppress unused var warning
            if (jacobian__)
                b_3 = in__.scalar_constrain(lp__);
            else
                b_3 = in__.scalar_constrain();

            local_scalar_t__ c_3;
            (void) c_3;  // dummy to suppress unused var warning
            if (jacobian__)
                c_3 = in__.scalar_constrain(lp__);
            else
                c_3 = in__.scalar_constrain();

            local_scalar_t__ alpha_3;
            (void) alpha_3;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha_3 = in__.scalar_constrain(lp__);
            else
                alpha_3 = in__.scalar_constrain();

            local_scalar_t__ w_4;
            (void) w_4;  // dummy to suppress unused var warning
            if (jacobian__)
                w_4 = in__.scalar_lb_constrain(0,lp__);
            else
                w_4 = in__.scalar_lb_constrain(0);

            local_scalar_t__ alpha_4;
            (void) alpha_4;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha_4 = in__.scalar_constrain(lp__);
            else
                alpha_4 = in__.scalar_constrain();

            local_scalar_t__ beta_4;
            (void) beta_4;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_4 = in__.scalar_constrain(lp__);
            else
                beta_4 = in__.scalar_constrain();

            local_scalar_t__ delta_4;
            (void) delta_4;  // dummy to suppress unused var warning
            if (jacobian__)
                delta_4 = in__.scalar_constrain(lp__);
            else
                delta_4 = in__.scalar_constrain();

            local_scalar_t__ kappa_4;
            (void) kappa_4;  // dummy to suppress unused var warning
            if (jacobian__)
                kappa_4 = in__.scalar_constrain(lp__);
            else
                kappa_4 = in__.scalar_constrain();

            local_scalar_t__ w_5;
            (void) w_5;  // dummy to suppress unused var warning
            if (jacobian__)
                w_5 = in__.scalar_lb_constrain(0,lp__);
            else
                w_5 = in__.scalar_lb_constrain(0);

            local_scalar_t__ a_5;
            (void) a_5;  // dummy to suppress unused var warning
            if (jacobian__)
                a_5 = in__.scalar_constrain(lp__);
            else
                a_5 = in__.scalar_constrain();

            local_scalar_t__ b_5;
            (void) b_5;  // dummy to suppress unused var warning
            if (jacobian__)
                b_5 = in__.scalar_constrain(lp__);
            else
                b_5 = in__.scalar_constrain();

            local_scalar_t__ c_5;
            (void) c_5;  // dummy to suppress unused var warning
            if (jacobian__)
                c_5 = in__.scalar_constrain(lp__);
            else
                c_5 = in__.scalar_constrain();

            local_scalar_t__ alpha_5;
            (void) alpha_5;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha_5 = in__.scalar_constrain(lp__);
            else
                alpha_5 = in__.scalar_constrain();

            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0,lp__);
            else
                sigma = in__.scalar_lb_constrain(0);


            // transformed parameters



            // validate transformed parameters

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            // model body
            {
            current_statement_begin__ = 82;
            validate_non_negative_index("ypred", "N", N);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  ypred(static_cast<Eigen::VectorXd::Index>(N));
            (void) ypred;  // dummy to suppress unused var warning

            stan::math::initialize(ypred, DUMMY_VAR__);
            stan::math::fill(ypred,DUMMY_VAR__);


            current_statement_begin__ = 84;
            lp_accum__.add(normal_log<propto__>(w_0, 1, 1));
            current_statement_begin__ = 85;
            lp_accum__.add(normal_log<propto__>(w_1, 1, 1));
            current_statement_begin__ = 86;
            lp_accum__.add(normal_log<propto__>(w_2, 1, 1));
            current_statement_begin__ = 87;
            lp_accum__.add(normal_log<propto__>(w_3, 1, 1));
            current_statement_begin__ = 88;
            lp_accum__.add(normal_log<propto__>(w_4, 1, 1));
            current_statement_begin__ = 89;
            lp_accum__.add(normal_log<propto__>(w_5, 1, 1));
            current_statement_begin__ = 90;
            lp_accum__.add(normal_log<propto__>(sigma, 0, 1));
            current_statement_begin__ = 92;
            lp_accum__.add(curveSlopeDist_log<propto__>(a_0, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 93;
            lp_accum__.add(curveSlopeDist_log<propto__>(b_0, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 94;
            lp_accum__.add(curveSlopeDist_log<propto__>(c_1, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 95;
            lp_accum__.add(curveSlopeDist_log<propto__>(a_1, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 96;
            lp_accum__.add(curveSlopeDist_log<propto__>(alpha_1, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 97;
            lp_accum__.add(curveSlopeDist_log<propto__>(a_2, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 98;
            lp_accum__.add(curveSlopeDist_log<propto__>(b_2, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 99;
            lp_accum__.add(curveSlopeDist_log<propto__>(c_2, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 100;
            lp_accum__.add(curveSlopeDist_log<propto__>(a_3, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 101;
            lp_accum__.add(curveSlopeDist_log<propto__>(b_3, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 102;
            lp_accum__.add(curveSlopeDist_log<propto__>(c_3, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 103;
            lp_accum__.add(curveSlopeDist_log<propto__>(alpha_3, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 104;
            lp_accum__.add(curveSlopeDist_log<propto__>(alpha_4, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 105;
            lp_accum__.add(curveSlopeDist_log<propto__>(beta_4, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 106;
            lp_accum__.add(curveSlopeDist_log<propto__>(delta_4, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 107;
            lp_accum__.add(curveSlopeDist_log<propto__>(kappa_4, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 108;
            lp_accum__.add(curveSlopeDist_log<propto__>(a_5, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 109;
            lp_accum__.add(curveSlopeDist_log<propto__>(b_5, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 110;
            lp_accum__.add(curveSlopeDist_log<propto__>(c_5, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 111;
            lp_accum__.add(curveSlopeDist_log<propto__>(alpha_5, w_0, w_1, w_2, w_3, w_4, w_5, a_0, b_0, c_1, a_1, alpha_1, a_2, b_2, c_2, a_3, b_3, c_3, alpha_3, alpha_4, beta_4, delta_4, kappa_4, a_5, b_5, c_5, alpha_5, m, pstream__));
            current_statement_begin__ = 113;
            lp_accum__.add(normal_log<propto__>(a_0, 0.5, 0.5));
            current_statement_begin__ = 114;
            lp_accum__.add(normal_log<propto__>(b_0, 1, 1));
            current_statement_begin__ = 115;
            lp_accum__.add(normal_log<propto__>(c_1, 1, 1));
            current_statement_begin__ = 116;
            lp_accum__.add(normal_log<propto__>(a_1, 10, 5));
            current_statement_begin__ = 117;
            lp_accum__.add(normal_log<propto__>(alpha_1, 0.5, 0.5));
            current_statement_begin__ = 118;
            lp_accum__.add(normal_log<propto__>(a_2, 1, 0.20000000000000001));
            current_statement_begin__ = 119;
            lp_accum__.add(normal_log<propto__>(b_2, 5, 2));
            current_statement_begin__ = 120;
            lp_accum__.add(normal_log<propto__>(c_2, -(1), 0.5));
            current_statement_begin__ = 121;
            lp_accum__.add(normal_log<propto__>(a_3, 0.20000000000000001, 0.10000000000000001));
            current_statement_begin__ = 122;
            lp_accum__.add(normal_log<propto__>(b_3, 0, 1));
            current_statement_begin__ = 123;
            lp_accum__.add(normal_log<propto__>(c_3, 1, 0.29999999999999999));
            current_statement_begin__ = 124;
            lp_accum__.add(normal_log<propto__>(alpha_3, 0.25, 0.25));
            current_statement_begin__ = 125;
            lp_accum__.add(normal_log<propto__>(alpha_4, 1.5, 0.5));
            current_statement_begin__ = 126;
            lp_accum__.add(normal_log<propto__>(beta_4, -(1), 1));
            current_statement_begin__ = 127;
            lp_accum__.add(normal_log<propto__>(delta_4, 0.5, 0.25));
            current_statement_begin__ = 128;
            lp_accum__.add(normal_log<propto__>(kappa_4, 0.5, 0.25));
            current_statement_begin__ = 129;
            lp_accum__.add(normal_log<propto__>(a_5, 0.10000000000000001, 0.050000000000000003));
            current_statement_begin__ = 130;
            lp_accum__.add(normal_log<propto__>(b_5, 0, 0.5));
            current_statement_begin__ = 131;
            lp_accum__.add(normal_log<propto__>(c_5, 1, 0.29999999999999999));
            current_statement_begin__ = 132;
            lp_accum__.add(normal_log<propto__>(alpha_5, 0.5, 0.20000000000000001));
            current_statement_begin__ = 137;
            for (int n = 1; n <= N; ++n) {
                current_statement_begin__ = 138;
                stan::model::assign(ypred, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            f_comb(w_0,w_1,w_2,w_3,w_4,w_5,a_0,b_0,c_1,a_1,alpha_1,a_2,b_2,c_2,a_3,b_3,c_3,alpha_3,alpha_4,beta_4,delta_4,kappa_4,a_5,b_5,c_5,alpha_5,get_base1(x,n,"x",1), pstream__), 
                            "assigning variable ypred");
            }
            current_statement_begin__ = 140;
            lp_accum__.add(normal_log<propto__>(y, ypred, sigma));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("w_0");
        names__.push_back("a_0");
        names__.push_back("b_0");
        names__.push_back("w_1");
        names__.push_back("c_1");
        names__.push_back("a_1");
        names__.push_back("alpha_1");
        names__.push_back("w_2");
        names__.push_back("a_2");
        names__.push_back("b_2");
        names__.push_back("c_2");
        names__.push_back("w_3");
        names__.push_back("a_3");
        names__.push_back("b_3");
        names__.push_back("c_3");
        names__.push_back("alpha_3");
        names__.push_back("w_4");
        names__.push_back("alpha_4");
        names__.push_back("beta_4");
        names__.push_back("delta_4");
        names__.push_back("kappa_4");
        names__.push_back("w_5");
        names__.push_back("a_5");
        names__.push_back("b_5");
        names__.push_back("c_5");
        names__.push_back("alpha_5");
        names__.push_back("sigma");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "LearningCurveOld_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double w_0 = in__.scalar_lb_constrain(0);
        double a_0 = in__.scalar_constrain();
        double b_0 = in__.scalar_constrain();
        double w_1 = in__.scalar_lb_constrain(0);
        double c_1 = in__.scalar_constrain();
        double a_1 = in__.scalar_constrain();
        double alpha_1 = in__.scalar_constrain();
        double w_2 = in__.scalar_lb_constrain(0);
        double a_2 = in__.scalar_constrain();
        double b_2 = in__.scalar_constrain();
        double c_2 = in__.scalar_constrain();
        double w_3 = in__.scalar_lb_constrain(0);
        double a_3 = in__.scalar_constrain();
        double b_3 = in__.scalar_constrain();
        double c_3 = in__.scalar_constrain();
        double alpha_3 = in__.scalar_constrain();
        double w_4 = in__.scalar_lb_constrain(0);
        double alpha_4 = in__.scalar_constrain();
        double beta_4 = in__.scalar_constrain();
        double delta_4 = in__.scalar_constrain();
        double kappa_4 = in__.scalar_constrain();
        double w_5 = in__.scalar_lb_constrain(0);
        double a_5 = in__.scalar_constrain();
        double b_5 = in__.scalar_constrain();
        double c_5 = in__.scalar_constrain();
        double alpha_5 = in__.scalar_constrain();
        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(w_0);
        vars__.push_back(a_0);
        vars__.push_back(b_0);
        vars__.push_back(w_1);
        vars__.push_back(c_1);
        vars__.push_back(a_1);
        vars__.push_back(alpha_1);
        vars__.push_back(w_2);
        vars__.push_back(a_2);
        vars__.push_back(b_2);
        vars__.push_back(c_2);
        vars__.push_back(w_3);
        vars__.push_back(a_3);
        vars__.push_back(b_3);
        vars__.push_back(c_3);
        vars__.push_back(alpha_3);
        vars__.push_back(w_4);
        vars__.push_back(alpha_4);
        vars__.push_back(beta_4);
        vars__.push_back(delta_4);
        vars__.push_back(kappa_4);
        vars__.push_back(w_5);
        vars__.push_back(a_5);
        vars__.push_back(b_5);
        vars__.push_back(c_5);
        vars__.push_back(alpha_5);
        vars__.push_back(sigma);

        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {



            // validate transformed parameters

            // write transformed parameters
            if (include_tparams__) {
            }
            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "LearningCurveOld_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "c_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "c_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "c_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "beta_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "delta_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "kappa_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "c_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }


        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "c_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "c_2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "c_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_3";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "beta_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "delta_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "kappa_4";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "w_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "c_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "alpha_5";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }


        if (!include_gqs__) return;
    }

}; // model

}

typedef LearningCurveOld_model_namespace::LearningCurveOld_model stan_model;

