// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PCSBasedComponentParameter.proto

package ai.libs.hasco.pcsbasedoptimization.proto;

/**
 * Protobuf type {@code pcsbasedoptimization.PCSBasedParameterProto}
 */
public final class PCSBasedParameterProto extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:pcsbasedoptimization.PCSBasedParameterProto)
		PCSBasedParameterProtoOrBuilder {
	private static final long serialVersionUID = 0L;

	// Use PCSBasedParameterProto.newBuilder() to construct.
	private PCSBasedParameterProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private PCSBasedParameterProto() {
		this.key_ = "";
		this.value_ = "";
	}

	@java.lang.Override
	@SuppressWarnings({ "unused" })
	protected java.lang.Object newInstance(final UnusedPrivateParameter unused) {
		return new PCSBasedParameterProto();
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return this.unknownFields;
	}

	private PCSBasedParameterProto(final com.google.protobuf.CodedInputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		if (extensionRegistry == null) {
			throw new java.lang.NullPointerException();
		}
		com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				case 10: {
					java.lang.String s = input.readStringRequireUtf8();

					this.key_ = s;
					break;
				}
				case 18: {
					java.lang.String s = input.readStringRequireUtf8();

					this.value_ = s;
					break;
				}
				default: {
					if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
						done = true;
					}
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		} catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
		} finally {
			this.unknownFields = unknownFields.build();
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedParameterProto_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedParameterProto_fieldAccessorTable
				.ensureFieldAccessorsInitialized(ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto.class, ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto.Builder.class);
	}

	public static final int KEY_FIELD_NUMBER = 1;
	private volatile java.lang.Object key_;

	/**
	 * <code>string key = 1;</code>
	 */
	@Override
	public java.lang.String getKey() {
		java.lang.Object ref = this.key_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			this.key_ = s;
			return s;
		}
	}

	/**
	 * <code>string key = 1;</code>
	 */
	@Override
	public com.google.protobuf.ByteString getKeyBytes() {
		java.lang.Object ref = this.key_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			this.key_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	public static final int VALUE_FIELD_NUMBER = 2;
	private volatile java.lang.Object value_;

	/**
	 * <code>string value = 2;</code>
	 */
	@Override
	public java.lang.String getValue() {
		java.lang.Object ref = this.value_;
		if (ref instanceof java.lang.String) {
			return (java.lang.String) ref;
		} else {
			com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
			java.lang.String s = bs.toStringUtf8();
			this.value_ = s;
			return s;
		}
	}

	/**
	 * <code>string value = 2;</code>
	 */
	@Override
	public com.google.protobuf.ByteString getValueBytes() {
		java.lang.Object ref = this.value_;
		if (ref instanceof java.lang.String) {
			com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
			this.value_ = b;
			return b;
		} else {
			return (com.google.protobuf.ByteString) ref;
		}
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = this.memoizedIsInitialized;
		if (isInitialized == 1) {
			return true;
		}
		if (isInitialized == 0) {
			return false;
		}

		this.memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(final com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (!this.getKeyBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 1, this.key_);
		}
		if (!this.getValueBytes().isEmpty()) {
			com.google.protobuf.GeneratedMessageV3.writeString(output, 2, this.value_);
		}
		unknownFields.writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1) {
			return size;
		}

		size = 0;
		if (!this.getKeyBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, this.key_);
		}
		if (!this.getValueBytes().isEmpty()) {
			size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, this.value_);
		}
		size += unknownFields.getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto)) {
			return super.equals(obj);
		}
		ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto other = (ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto) obj;

		if (!this.getKey().equals(other.getKey())) {
			return false;
		}
		if (!this.getValue().equals(other.getValue())) {
			return false;
		}
		if (!unknownFields.equals(other.unknownFields)) {
			return false;
		}
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + KEY_FIELD_NUMBER;
		hash = (53 * hash) + this.getKey().hashCode();
		hash = (37 * hash) + VALUE_FIELD_NUMBER;
		hash = (53 * hash) + this.getValue().hashCode();
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final java.nio.ByteBuffer data, final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final com.google.protobuf.ByteString data, final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final byte[] data, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final java.io.InputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseDelimitedFrom(final java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseDelimitedFrom(final java.io.InputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parseFrom(final com.google.protobuf.CodedInputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(final ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code pcsbasedoptimization.PCSBasedParameterProto}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:pcsbasedoptimization.PCSBasedParameterProto)
			ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProtoOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedParameterProto_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedParameterProto_fieldAccessorTable
					.ensureFieldAccessorsInitialized(ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto.class, ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto.Builder.class);
		}

		// Construct using ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto.newBuilder()
		private Builder() {
			this.maybeForceBuilderInitialization();
		}

		private Builder(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);
			this.maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
			}
		}

		@java.lang.Override
		public Builder clear() {
			super.clear();
			this.key_ = "";

			this.value_ = "";

			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedParameterProto_descriptor;
		}

		@java.lang.Override
		public ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto getDefaultInstanceForType() {
			return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto.getDefaultInstance();
		}

		@java.lang.Override
		public ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto build() {
			ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto result = this.buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto buildPartial() {
			ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto result = new ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto(this);
			result.key_ = this.key_;
			result.value_ = this.value_;
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}

		@java.lang.Override
		public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field, final java.lang.Object value) {
			return super.setField(field, value);
		}

		@java.lang.Override
		public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		@java.lang.Override
		public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@java.lang.Override
		public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field, final int index, final java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@java.lang.Override
		public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field, final java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}

		@java.lang.Override
		public Builder mergeFrom(final com.google.protobuf.Message other) {
			if (other instanceof ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto) {
				return this.mergeFrom((ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(final ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto other) {
			if (other == ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto.getDefaultInstance()) {
				return this;
			}
			if (!other.getKey().isEmpty()) {
				this.key_ = other.key_;
				onChanged();
			}
			if (!other.getValue().isEmpty()) {
				this.value_ = other.value_;
				onChanged();
			}
			this.mergeUnknownFields(other.unknownFields);
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(final com.google.protobuf.CodedInputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto) e.getUnfinishedMessage();
				throw e.unwrapIOException();
			} finally {
				if (parsedMessage != null) {
					this.mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private java.lang.Object key_ = "";

		/**
		 * <code>string key = 1;</code>
		 */
		@Override
		public java.lang.String getKey() {
			java.lang.Object ref = this.key_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				this.key_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string key = 1;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getKeyBytes() {
			java.lang.Object ref = this.key_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				this.key_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string key = 1;</code>
		 */
		public Builder setKey(final java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			this.key_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>string key = 1;</code>
		 */
		public Builder clearKey() {

			this.key_ = getDefaultInstance().getKey();
			onChanged();
			return this;
		}

		/**
		 * <code>string key = 1;</code>
		 */
		public Builder setKeyBytes(final com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			this.key_ = value;
			onChanged();
			return this;
		}

		private java.lang.Object value_ = "";

		/**
		 * <code>string value = 2;</code>
		 */
		@Override
		public java.lang.String getValue() {
			java.lang.Object ref = this.value_;
			if (!(ref instanceof java.lang.String)) {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				this.value_ = s;
				return s;
			} else {
				return (java.lang.String) ref;
			}
		}

		/**
		 * <code>string value = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getValueBytes() {
			java.lang.Object ref = this.value_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				this.value_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		/**
		 * <code>string value = 2;</code>
		 */
		public Builder setValue(final java.lang.String value) {
			if (value == null) {
				throw new NullPointerException();
			}

			this.value_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>string value = 2;</code>
		 */
		public Builder clearValue() {

			this.value_ = getDefaultInstance().getValue();
			onChanged();
			return this;
		}

		/**
		 * <code>string value = 2;</code>
		 */
		public Builder setValueBytes(final com.google.protobuf.ByteString value) {
			if (value == null) {
				throw new NullPointerException();
			}
			checkByteStringIsUtf8(value);

			this.value_ = value;
			onChanged();
			return this;
		}

		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:pcsbasedoptimization.PCSBasedParameterProto)
	}

	// @@protoc_insertion_point(class_scope:pcsbasedoptimization.PCSBasedParameterProto)
	private static final ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto();
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<PCSBasedParameterProto> PARSER = new com.google.protobuf.AbstractParser<PCSBasedParameterProto>() {
		@java.lang.Override
		public PCSBasedParameterProto parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return new PCSBasedParameterProto(input, extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<PCSBasedParameterProto> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<PCSBasedParameterProto> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedParameterProto getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
