// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PCSBasedComponentParameter.proto

package ai.libs.hasco.pcsbasedoptimization.proto;

public interface PCSBasedEvaluationResponseProtoOrBuilder extends
		// @@protoc_insertion_point(interface_extends:pcsbasedoptimization.PCSBasedEvaluationResponseProto)
		com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>double result = 1;</code>
	 */
	double getResult();
}
