// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PCSBasedComponentParameter.proto

package ai.libs.hasco.pcsbasedoptimization.proto;

public final class PCSBasedComponentParameter {
	private PCSBasedComponentParameter() {
	}

	public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	static final com.google.protobuf.Descriptors.Descriptor internal_static_pcsbasedoptimization_PCSBasedComponentProto_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_pcsbasedoptimization_PCSBasedComponentProto_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_pcsbasedoptimization_PCSBasedParameterProto_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_pcsbasedoptimization_PCSBasedParameterProto_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n PCSBasedComponentParameter.proto\022\024pcsb" + "asedoptimization\"h\n\026PCSBasedComponentPro" + "to\022\014\n\004name\030\001 \001(\t\022@\n\nparameters\030\002 \003(\0132,.p"
				+ "csbasedoptimization.PCSBasedParameterPro" + "to\"4\n\026PCSBasedParameterProto\022\013\n\003key\030\001 \001(" + "\t\022\r\n\005value\030\002 \001(\t\"1\n\037PCSBasedEvaluationRe"
				+ "sponseProto\022\016\n\006result\030\001 \001(\0012\215\001\n\030PCSBased" + "OptimizerService\022q\n\010Evaluate\022,.pcsbasedo" + "ptimization.PCSBasedComponentProto\0325.pcs" + "basedoptimization.PCSBasedEvaluationResp"
				+ "onseProto\"\000B/\n(ai.libs.hasco.pcsbasedopt" + "imization.protoP\001\210\001\001b\006proto3" };
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
		internal_static_pcsbasedoptimization_PCSBasedComponentProto_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_pcsbasedoptimization_PCSBasedComponentProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_pcsbasedoptimization_PCSBasedComponentProto_descriptor,
				new java.lang.String[] { "Name", "Parameters", });
		internal_static_pcsbasedoptimization_PCSBasedParameterProto_descriptor = getDescriptor().getMessageTypes().get(1);
		internal_static_pcsbasedoptimization_PCSBasedParameterProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_pcsbasedoptimization_PCSBasedParameterProto_descriptor,
				new java.lang.String[] { "Key", "Value", });
		internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_descriptor = getDescriptor().getMessageTypes().get(2);
		internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_descriptor,
				new java.lang.String[] { "Result", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
