// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PCSBasedComponentParameter.proto

package ai.libs.hasco.pcsbasedoptimization.proto;

/**
 * Protobuf type {@code pcsbasedoptimization.PCSBasedEvaluationResponseProto}
 */
public final class PCSBasedEvaluationResponseProto extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:pcsbasedoptimization.PCSBasedEvaluationResponseProto)
		PCSBasedEvaluationResponseProtoOrBuilder {
	private static final long serialVersionUID = 0L;

	// Use PCSBasedEvaluationResponseProto.newBuilder() to construct.
	private PCSBasedEvaluationResponseProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}

	private PCSBasedEvaluationResponseProto() {
	}

	@java.lang.Override
	@SuppressWarnings({ "unused" })
	protected java.lang.Object newInstance(final UnusedPrivateParameter unused) {
		return new PCSBasedEvaluationResponseProto();
	}

	@java.lang.Override
	public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
		return this.unknownFields;
	}

	private PCSBasedEvaluationResponseProto(final com.google.protobuf.CodedInputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
		this();
		if (extensionRegistry == null) {
			throw new java.lang.NullPointerException();
		}
		com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
		try {
			boolean done = false;
			while (!done) {
				int tag = input.readTag();
				switch (tag) {
				case 0:
					done = true;
					break;
				case 9: {

					this.result_ = input.readDouble();
					break;
				}
				default: {
					if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
						done = true;
					}
					break;
				}
				}
			}
		} catch (com.google.protobuf.InvalidProtocolBufferException e) {
			throw e.setUnfinishedMessage(this);
		} catch (java.io.IOException e) {
			throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
		} finally {
			this.unknownFields = unknownFields.build();
			makeExtensionsImmutable();
		}
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_fieldAccessorTable
				.ensureFieldAccessorsInitialized(ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto.class, ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto.Builder.class);
	}

	public static final int RESULT_FIELD_NUMBER = 1;
	private double result_;

	/**
	 * <code>double result = 1;</code>
	 */
	@Override
	public double getResult() {
		return this.result_;
	}

	private byte memoizedIsInitialized = -1;

	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = this.memoizedIsInitialized;
		if (isInitialized == 1) {
			return true;
		}
		if (isInitialized == 0) {
			return false;
		}

		this.memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(final com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		if (this.result_ != 0D) {
			output.writeDouble(1, this.result_);
		}
		unknownFields.writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1) {
			return size;
		}

		size = 0;
		if (this.result_ != 0D) {
			size += com.google.protobuf.CodedOutputStream.computeDoubleSize(1, this.result_);
		}
		size += unknownFields.getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto)) {
			return super.equals(obj);
		}
		ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto other = (ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto) obj;

		if (java.lang.Double.doubleToLongBits(this.getResult()) != java.lang.Double.doubleToLongBits(other.getResult())) {
			return false;
		}
		if (!unknownFields.equals(other.unknownFields)) {
			return false;
		}
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (37 * hash) + RESULT_FIELD_NUMBER;
		hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(this.getResult()));
		hash = (29 * hash) + unknownFields.hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final java.nio.ByteBuffer data, final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final com.google.protobuf.ByteString data, final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final byte[] data, final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final java.io.InputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseDelimitedFrom(final java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseDelimitedFrom(final java.io.InputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parseFrom(final com.google.protobuf.CodedInputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}

	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}

	public static Builder newBuilder(final ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}

	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}

	/**
	 * Protobuf type {@code pcsbasedoptimization.PCSBasedEvaluationResponseProto}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:pcsbasedoptimization.PCSBasedEvaluationResponseProto)
			ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProtoOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_fieldAccessorTable
					.ensureFieldAccessorsInitialized(ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto.class, ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto.Builder.class);
		}

		// Construct using ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto.newBuilder()
		private Builder() {
			this.maybeForceBuilderInitialization();
		}

		private Builder(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);
			this.maybeForceBuilderInitialization();
		}

		private void maybeForceBuilderInitialization() {
			if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
			}
		}

		@java.lang.Override
		public Builder clear() {
			super.clear();
			this.result_ = 0D;

			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedComponentParameter.internal_static_pcsbasedoptimization_PCSBasedEvaluationResponseProto_descriptor;
		}

		@java.lang.Override
		public ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto getDefaultInstanceForType() {
			return ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto.getDefaultInstance();
		}

		@java.lang.Override
		public ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto build() {
			ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto result = this.buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto buildPartial() {
			ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto result = new ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto(this);
			result.result_ = this.result_;
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}

		@java.lang.Override
		public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field, final java.lang.Object value) {
			return super.setField(field, value);
		}

		@java.lang.Override
		public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}

		@java.lang.Override
		public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}

		@java.lang.Override
		public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field, final int index, final java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}

		@java.lang.Override
		public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field, final java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}

		@java.lang.Override
		public Builder mergeFrom(final com.google.protobuf.Message other) {
			if (other instanceof ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto) {
				return this.mergeFrom((ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(final ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto other) {
			if (other == ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto.getDefaultInstance()) {
				return this;
			}
			if (other.getResult() != 0D) {
				this.setResult(other.getResult());
			}
			this.mergeUnknownFields(other.unknownFields);
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(final com.google.protobuf.CodedInputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto parsedMessage = null;
			try {
				parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				parsedMessage = (ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto) e.getUnfinishedMessage();
				throw e.unwrapIOException();
			} finally {
				if (parsedMessage != null) {
					this.mergeFrom(parsedMessage);
				}
			}
			return this;
		}

		private double result_;

		/**
		 * <code>double result = 1;</code>
		 */
		@Override
		public double getResult() {
			return this.result_;
		}

		/**
		 * <code>double result = 1;</code>
		 */
		public Builder setResult(final double value) {

			this.result_ = value;
			onChanged();
			return this;
		}

		/**
		 * <code>double result = 1;</code>
		 */
		public Builder clearResult() {

			this.result_ = 0D;
			onChanged();
			return this;
		}

		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:pcsbasedoptimization.PCSBasedEvaluationResponseProto)
	}

	// @@protoc_insertion_point(class_scope:pcsbasedoptimization.PCSBasedEvaluationResponseProto)
	private static final ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto();
	}

	public static ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<PCSBasedEvaluationResponseProto> PARSER = new com.google.protobuf.AbstractParser<PCSBasedEvaluationResponseProto>() {
		@java.lang.Override
		public PCSBasedEvaluationResponseProto parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return new PCSBasedEvaluationResponseProto(input, extensionRegistry);
		}
	};

	public static com.google.protobuf.Parser<PCSBasedEvaluationResponseProto> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<PCSBasedEvaluationResponseProto> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public ai.libs.hasco.pcsbasedoptimization.proto.PCSBasedEvaluationResponseProto getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
