package jaicore.ml.measures;

public enum PMMulticlass {
    areaAboveROC,
    areaUnderROC,
    avgCost,
    correct,
    correlationCoefficient,
    errorRate,
    falseNegativeRate,
    falsePositiveRate,
    fMeasure,
    incorrect,
    kappa,
    kBInformation,
    kBMeanInformation,
    kBRelativeInformation,
    meanAbsoluteError,
    pctCorrect,
    pctIncorrect,
    precision,
    relativeAbsoluteError,
    rootMeanSquaredError,
    rootRelativeSquaredError,
    weightedAreaUnderROC,
    weightedFalseNegativeRate,
    weightedFalsePositiveRate,
    weightedFMeasure,
    weightedPrecision,
    weightedRecall,
    weightedTrueNegativeRate,
    weightedTruePositiveRate
}
