package hasco.serialization;

public class ComponentNotFoundException extends Exception {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -8112109551741268191L;

	public ComponentNotFoundException() {
		super();
	}

	public ComponentNotFoundException(String message) {
		super(message);
	}

	public ComponentNotFoundException(Throwable cause) {
		super(cause);
	}

	public ComponentNotFoundException(String message, Throwable cause) {
		super(message, cause);
	}
}
